services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelconsult\KiChatbot\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Pixelconsult\KiChatbot\Controller\BackendController:
    public: true
